#Enable future-style type annotations
from __future__ import annotations
#Import matplotlib for plotting and visualization
import matplotlib.pyplot as plt
#Import pandas for data manipulation (used indirectly in Scanpy workflows)
import pandas as pd
#Import Scanpy, the main library for single-cell RNA-seq analysis
import scanpy as sc
import warnings
warnings.filterwarnings("ignore")

## Setting for scanpy
#Set Scanpy logging verbosity level
sc.settings.verbosity = 0

# Set PNG as default format for all figures
sc.settings.file_format_figs = 'png'
plt.rcParams['savefig.format'] = 'png'

#Set default figure parameters for Scanpy-generated plots
sc.set_figure_params(dpi=80, facecolor="white")

#Print Scanpy version and system information for reproducibility
sc.logging.print_header()

#Define the directory where all figures generated by Scanpy will be saved
sc.settings.figdir = "/home/StudentFirst/git/BIOT670I-Group_Project/write/figures"

#Define the output files to store the processed AnnData objects at each step
preprocessing_file = "/home/StudentFirst/git/BIOT670I-Group_Project/write/pbmc3k_preprocessing.h5ad"
pca_file = "/home/StudentFirst/git/BIOT670I-Group_Project/write/pbmc3k_pca.h5ad"
clustering_file = "/home/StudentFirst/git/BIOT670I-Group_Project/write/pbmc3k_clustering.h5ad"
annotated_file = "/home/StudentFirst/git/BIOT670I-Group_Project/write/pbmc3k_annotated.h5ad"

# 1. Load the data
#Read in the 10X Genomics formatted gene expression matrix
adata = sc.read_10x_mtx(
    "data/filtered_gene_bc_matrices/hg19/",
    var_names="gene_symbols",
    cache=True,
)

print("Original Data info:")
print(adata, '\n')

adata.var_names_make_unique()

# 2. Preprocessing
print("Starting preprocessing...")

sc.pl.highest_expr_genes(adata, n_top=20, save="_highest_expr.png")

sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)

print("After filtering data: ")
print(adata, '\n')

adata.var["mt"] = adata.var_names.str.startswith("MT-")
sc.pp.calculate_qc_metrics(adata, qc_vars=["mt"], percent_top=None, log1p=False, inplace=True)

sc.pl.violin(
    adata,
    ["n_genes_by_counts", "total_counts", "pct_counts_mt"],
    jitter=0.4,
    multi_panel=True, 
    save="_violin.png"
)

fig, axs = plt.subplots(1, 2, figsize=(10, 4), layout="constrained")
sc.pl.scatter(adata, x="total_counts", y="pct_counts_mt", show=False, ax=axs[0])
sc.pl.scatter(adata, x="total_counts", y="n_genes_by_counts", show=False, ax=axs[1])
plt.savefig(f"{sc.settings.figdir}/scatter_qc.png", dpi=300, bbox_inches='tight')
plt.close()

# QC filtering
adata = adata[
    (adata.obs.n_genes_by_counts < 2500) & 
    (adata.obs.n_genes_by_counts > 200) & 
    (adata.obs.pct_counts_mt < 5),
    :,
].copy()

adata.layers["counts"] = adata.X.copy()

print("After QC filtering:")
print(adata, '\n')

# Normalization
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

# Highly variable genes
sc.pp.highly_variable_genes(adata, layer="counts", n_top_genes=2000, 
                           min_mean=0.0125, max_mean=3, min_disp=0.5, flavor="seurat_v3")
sc.pl.highly_variable_genes(adata, save="_hvg.png")

# Scaling
adata.layers["scaled"] = adata.X.toarray()
sc.pp.regress_out(adata, ["total_counts", "pct_counts_mt"], layer="scaled")
sc.pp.scale(adata, max_value=10, layer="scaled")

# Save preprocessing results
adata.write(preprocessing_file)
print("Preprocessing DONE!")
print(f"Preprocessing results saved to: {preprocessing_file}\n")

# 3. PCA Analysis
print("Starting PCA analysis...")

sc.pp.pca(adata, use_highly_variable=True, layer="scaled")
sc.pl.pca(adata, save="_pca.png")
sc.pl.pca_loadings(adata, save="_pca_loadings.png")
sc.pl.pca_variance_ratio(adata, log=True, save="_pca_variance.png")

# Save PCA results
adata.write(pca_file)
print("PCA analysis DONE!")
print(f"PCA results saved to: {pca_file}\n")

# 4. Clustering Analysis
print("Starting clustering analysis...")

sc.pp.neighbors(adata, n_neighbors=10, n_pcs=30)
sc.tl.leiden(adata, resolution=0.5)
sc.tl.umap(adata)
sc.tl.tsne(adata)

# Plot clustering results (single set of plots)
sc.pl.umap(adata, color='leiden', save="_umap_leiden.png")
sc.pl.tsne(adata, color='leiden', save="_tsne_leiden.png")

# Save clustering results
adata.write(clustering_file)
print("Clustering analysis DONE!")
print(f"Clustering results saved to: {clustering_file}\n")

# 5. Cell Type Annotation 
print("Annotating clusters with biological cell types...")

celltype_annotations = {
    "0": "CD4 T cells",
    "1": "B cells", 
    "2": "CD14+ Monocytes",
    "3": "NK cells",
    "4": "CD8 T cells",
    "5": "FCGR3A+ Monocytes",
    "6": "Dendritic cells",
    "7": "Megakaryocytes"
}

adata.obs["cell_type"] = adata.obs["leiden"].map(celltype_annotations)
print("Cell type annotation complete.")
print(adata.obs[["leiden","cell_type"]].head())

# Marker genes for visualization
canonical_markers = [
    "IL7R", "CCR7", "LTB",        # T cells
    "NKG7", "GNLY", "GZMB", "PRF1", # Cytotoxic T / NK
    "MS4A1", "CD79A", "CD79B",    # B cells
    "LYZ", "S100A8", "S100A9", "LGALS3", # Monocytes
    "FCER1A", "CST3",             # Dendritic cells
    "PPBP"                        # Megakaryocytes / platelets
]

marker_genes = [g for g in canonical_markers if g in adata.var_names]
print(f"Using {len(marker_genes)} marker genes for visualization.")

# Generate annotation plots
print("Plotting annotated results...")
sc.pl.umap(adata, color=["leiden","cell_type"], save="_clusters_annotated.png")

if marker_genes:
    sc.pl.umap(adata, color=marker_genes[:6], ncols=3, save="_markers.png")
    
    sc.pl.heatmap(
        adata,
        var_names=marker_genes,
        groupby="cell_type",
        use_raw=False,
        cmap="viridis",
        dendrogram=True,
        swap_axes=True,
        save="_marker_heatmap.png",
    )
    
    sc.pl.violin(
        adata,
        keys=marker_genes,
        groupby="cell_type", 
        rotation=90,
        multi_panel=True,
        save="_marker_violin.png",
    )
    
    sc.pl.dotplot(
        adata,
        var_names=marker_genes,
        groupby="cell_type",
        standard_scale="var",
        save="_marker_dotplot.png",
    )

# Save final annotated results
adata.write(annotated_file)

print("="*60)
print("ANALYSIS COMPLETE!")
print("="*60)
print("Generated h5ad files:")
print(f"1. Preprocessing: {preprocessing_file}")
print(f"2. PCA Analysis:  {pca_file}")
print(f"3. Clustering:    {clustering_file}")
print(f"4. Annotated:     {annotated_file}")

# List all generated figures
import os
import glob
png_files = glob.glob(f"{sc.settings.figdir}/*.png")
print(f"\nGenerated {len(png_files)} PNG files:")
for file in sorted(png_files):
    print(f"  - {os.path.basename(file)}")

# Show file sizes
print(f"\nFile sizes:")
for file_path, name in [(preprocessing_file, "Preprocessing"), 
                       (pca_file, "PCA"), 
                       (clustering_file, "Clustering"),
                       (annotated_file, "Annotated")]:
    if os.path.exists(file_path):
        size_mb = os.path.getsize(file_path) / (1024 * 1024)
        print(f"  {name}: {size_mb:.2f} MB")
