#-----scanpy_script_qc.py-----#

#Enable future-style type annotations
from __future__ import annotations

#Import operating system utilities for folder creation and file paths
import os

#Import matplotlib for plotting and visualization
import matplotlib.pyplot as plt

#Import pandas for data manipulation (used indirectly in Scanpy workflows)
import pandas as pd

#Import Scanpy, the main library for single-cell RNA-seq analysis
import scanpy as sc

#Import warnings and suppress non-critical warnings
import warnings
warnings.filterwarnings("ignore")

## Setting for scanpy
#Set Scanpy logging verbosity level
#0 = errors only, 1 = warnings, 2 = info, 3 = detailed hints
#Using a higher level helps track what Scanpy is doing internally
sc.settings.verbosity = 0

#Set default figure parameters for Scanpy-generated plots
#dpi controls resolution, facecolor sets background color
sc.set_figure_params(dpi=80, facecolor="white")

#Print Scanpy version and system information for reproducibility
sc.logging.print_header()

#Create output folders if they do not already exist
os.makedirs("write", exist_ok=True)
os.makedirs("write/figures", exist_ok=True)

#Define the directory where all figures generated by Scanpy will be saved
sc.settings.figdir = "write/figures"
sc.settings.file_format_figs = "png"

#Define the output file to store the processed AnnData object
#the file that will store the analysis results
results_file = "write/pbmc3k.h5ad"

# 1. Load the data
#Read in the 10X Genomics formatted gene expression matrix
#This loads the filtered feature-barcode matrix (counts data)
adata = sc.read_10x_mtx(
    "data/filtered_gene_bc_matrices/hg19/",  # the directory with the `.mtx` file
    var_names="gene_symbols",  # use gene symbols for the variable names (variables-axis index)
    cache=True,  # write a cache file for faster subsequent reading
)

#Print a summary of the AnnData object (cells × genes)
print("Original Data info:")
print(adata, "\n")

#Ensure gene names are unique to avoid downstream conflicts
adata.var_names_make_unique()  # this is unnecessary if using `var_names='gene_ids'` in `sc.read_10x_mtx`

# 2. Preprocessing
#Plot the genes with the highest total expression across all cells
#To show those genes that yield the highest fraction of counts in each single cell, across all cells.
#This plot caused compatibility issues earlier in your environment, so it is left commented out.
#sc.pl.highest_expr_genes(adata, n_top=20, save=".png")

#Filter out cells with very few detected genes
sc.pp.filter_cells(adata, min_genes=200)  # this does nothing, in this specific case

#Filter out genes that are detected in very few cells
sc.pp.filter_genes(adata, min_cells=3)

#Print updated AnnData dimensions after filtering
print("After filtering data: ")
print(adata, "\n")

#Annotate mitochondrial genes
#annotate the group of mitochondrial genes as "mt"
adata.var["mt"] = adata.var_names.str.startswith("MT-")

#Calculate quality control (QC) metrics that includes total counts, number of genes, and mitochondrial gene percentages
sc.pp.calculate_qc_metrics(adata, qc_vars=["mt"], percent_top=None, log1p=False, inplace=True)

#Visualize QC metrics using violin plots, this helps to decide filtering thresholds for low-quality cells
sc.pl.violin(
    adata,
    ["n_genes_by_counts", "total_counts", "pct_counts_mt"],
    jitter=0.4,
    multi_panel=True,
    save="_plot.png",
    show=False,
)

#To create scatter plots for QC relationships
fig, axs = plt.subplots(1, 2, figsize=(10, 4), layout="constrained")
sc.pl.scatter(adata, x="total_counts", y="pct_counts_mt", show=False, ax=axs[0])
sc.pl.scatter(adata, x="total_counts", y="n_genes_by_counts", show=False, ax=axs[1])
plt.savefig(os.path.join(sc.settings.figdir, "qc_scatter.png"), bbox_inches="tight")
plt.close(fig)

#To filter cells based on QC thresholds that remove cells with too many genes, too few genes, or high mitochondrial content
adata = adata[
    (adata.obs.n_genes_by_counts < 2500)
    & (adata.obs.n_genes_by_counts > 200)
    & (adata.obs.pct_counts_mt < 5),
    :,
].copy()

#To store raw counts in a separate layer for later use
adata.layers["counts"] = adata.X.copy()

#Print AnnData summary after QC filtering
print("After QC filtering:")
print(adata, "\n")

#Normalize total counts per cell to a fixed value (10,000)
sc.pp.normalize_total(adata, target_sum=1e4)

#Log-transform the normalized data that makes gene expression distributions more comparable
sc.pp.log1p(adata)

#Store log-normalized data in .raw for later reference
adata.raw = adata.copy()

#Identify highly variable genes (HVGs), HVGs capture the most biologically informative variation
sc.pp.highly_variable_genes(
    adata,
    layer="counts",
    n_top_genes=2000,
    min_mean=0.0125,
    max_mean=3,
    min_disp=0.5,
    flavor="seurat_v3",
)

#Plot highly variable genes
sc.pl.highly_variable_genes(adata, save=".png", show=False)

#Subset the dataset to only highly variable genes
adata = adata[:, adata.var.highly_variable].copy()

#Regress out technical covariates such as sequencing depth and mitochondrial content
#This runs on adata.X in Scanpy 1.9.8
sc.pp.regress_out(adata, ["total_counts", "pct_counts_mt"])

#Scale the data to unit variance and cap extreme values
sc.pp.scale(adata, max_value=10)

print("QC filtering DONE!")

#PART II PCA LEIDEN CLUSTERING

#PCA uses principal components to plot genes with most significant variation and usually will only show a couple dozen PCs. #
#Each dot is a single cell and physical proximity means the cells have similar gene expressions. #
#Clusters hint to different cell types or metabolic states and overlapping cells hint to similar gene expressions #

sc.tl.pca(adata, svd_solver="arpack")
sc.pl.pca(adata, save="_pca.png", show=False)

#If you are curious which genes are leading to the major principal components use the following to rank them#
sc.pl.pca_loadings(adata, save="_loadings.png", show=False)

#Another view of the data involves seeing how much each PC contributes to the overall variance for the number of PCs we had previously preselected. #
sc.pl.pca_variance_ratio(adata, log=True, save="_variance.png", show=False)

#Build a neighborhood graph connecting each cell to its nearest neighbors based on PCA coordinates #
#Cells with similar gene expression are connected. Here each cell is connected to 10 most similar other cells and 40 principal components are used. These numbers can be tweaked if needed. #
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=30)

# Cells are clustered using the Leiden algorithm which uses the nearest neighbor graph from the previous step#
#Similar cells are grouped-clustered together. #
#Higher than 1 lead to numerous small clusters while closer to zero leads to few large clusters. #
#UMAP converts cell and gene data into x and y coordinates to make a scatter plot. Then each cluster gets a different color for easier visualization. #
sc.tl.leiden(adata, resolution=0.5)
sc.tl.umap(adata)
sc.pl.umap(adata, color="leiden", save="_leiden.png", show=False)

#. tSNE can be preferred for smaller datasets with few close clusters. UMAP can be used for larger datasets and is faster. #
sc.tl.tsne(adata)
sc.pl.tsne(adata, color="leiden", save="_tsne.png", show=False)

#cell annotation

# --------------------------------
# Cell Type Annotation
# --------------------------------

celltype_annotations = {
    "0": "CD4 T cells",
    "1": "NK cells",
    "2": "B cells",
    "3": "CD14+ Monocytes",
    "4": "FCGR3A+ Monocytes",
    "5": "Dendritic cells",
    "6": "Platelets",
    "7": "CD8 T cells"
}

# Map Leiden clusters to cell types
adata.obs["cell type"] = adata.obs["leiden"].astype(str).map(celltype_annotations)

# Fill clusters not annotated
adata.obs["cell type"] = adata.obs["cell type"].fillna("Unknown").astype("category")

# Plot annotated clusters
sc.pl.umap(adata, color=["leiden", "cell type"], save="_celltypes.png", show=False)

# --------------------------------
# Save annotated dataset
# --------------------------------

output_file = "write/pbmc3k_annotated.h5ad"
adata.write(output_file)

# Also save a general processed file name if needed for the project pipeline
adata.write(results_file)

# Print completion message
print("Cell annotation complete.")
print("Annotated file saved as:", output_file)
print("Processed file also saved as:", results_file)
